Dev
phfdonda/enumerable pull request #1
Opened 2020-04-01 20:46 UTC by phfdonda

Complete project.
Thank you for your review and any insight you can give me! This was a very hard assignment, and any feedback would be very welcome! Thank you!

2020-04-01 21:36 UTC, kobiyoyo requested changes
## Hi @phfdonda    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Lets enable stickler 
- [ ] Pull Request should have a meaningful title
- [ ] Next project use a better branch name for example `enum_methods`
- [ ] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*) - should return 302400`

- [ ] `my_none?`:
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello'].my_none?(5)` - should return `true`
- [ ] `my_any?`:
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('cat')` should return `true`
- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`



- [ ] `my_all`  
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`p [3,3,3,3,4].my_all?(3)` should return` false`



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-01 22:52 UTC, phfdonda commented
I have made the changes requested, @kobiyoyo! Thank you for the excellent review!

2020-04-02 14:41 UTC, stratospherique requested changes
### Great Progress @phfdonda :clap: However, some methods still needs further refactoring in order for us to approve your project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods :gear: 

### That's it :relaxed: when finished, kindly resubmit another code review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-04-02 14:41 UTC, stratospherique commented on main.rb
> +  end
* [ ] `my_all?` is identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_all? when no block or argument is given returns true when none of the collection members are false or nil
  ```ruby
    array = [1,2,5,4,7]
    p array.my_all? == array.all? # false
  ```
* [ ] my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
  ```ruby
    array = [3,3,3,3,3]
    p array.my_all?(3) == array.all?(3) # false
  ```

2020-04-02 14:41 UTC, stratospherique commented on main.rb
> + end
* [ ] `my_any?` is identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_any? when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
  ```ruby
    array = %w[dog door rod blade]
    p array.my_any?('cat') == array.any?('cat') # false
  ```

2020-04-02 14:41 UTC, stratospherique commented on main.rb
> +  end
* [ ] `my_none?` is identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

* [ ] my_none? when no block or argument is given returns true only if none of the collection members is true
  ```ruby
    array = [nil, false, nil, false]
    p array.my_none? == array.none? # false
  ```

2020-04-02 15:51 UTC, phfdonda commented
Thank you, @stratospherique! I made the changes, and I believe it's all working now! That was a good tip, comparing to the original method. Thank you!

2020-04-02 23:21 UTC, kobiyoyo requested changes
## Hi @phfdonda    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, you are almost there .
### General

- [ ] `my_none?`:
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello',5].my_none?(5) `should return false




### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-03 13:32 UTC, phfdonda commented
Hi, @kobiyoyo. Thank you, silly mistake. Yeah, I think that's it now! Thank you for the review!

2020-04-03 14:24 UTC, Torres-ssf approved these changes
### Project Approved :tada:  :clap: 
Hi there @phfdonda 
Nice job implementing the requested changes.
All your methods are working properly now. :smile: 
**I'm approving this PR**
Good luck in the next project

**[TIP]**
- [ ] The .gitignore should be in the root of your project. And you should add both `.vscode` and `.idea`
(hidden on OS X). These two files are specific settings files(from vscode and IntelliJ’s) and should not be uploaded to GitHub.


Happy coding :computer: 
**Sergio Torres**

2020-04-03 14:37 UTC, merged